nodeLinker: "pnp"

packageExtensions:
  "babel-loader@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@mdx-js/loader@*":
    dependencies:
      "react": "*"
  "@mdx-js/react@*":
    dependencies:
      "react": "*"
  "@storybook/ui@*":
    dependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/builder-webpack5@*":
    dependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/manager-webpack5@*":
    dependencies:
      "react": "*"
      "react-dom": "*"
  "storybook-addon-turbo-build@*":
    dependencies:
      "webpack": "*"
  "@lightningjs/ui-components@*": 
    dependencies:
      "@lightningjs/core": "*"

changesetBaseRefs:
  - 'release'
  - 'origin/release'

npmAuthToken: "${NPM_TOKEN:-fallback}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
