nodeLinker: node-modules

npmScopes:
  lightning:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_PUBLISH_KEY:-fallback}"
    npmPublishRegistry: "https://artifactory.comcast.com/artifactory/api/npm/Lightning-npm-releases"
    npmRegistryServer: "https://artifactory.comcast.com/artifactory/api/npm/Lightning-npm"
  suite-themes:
    npmRegistryServer: "https://artifactory.comcast.com/artifactory/api/npm/xds-npm"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
