nodeLinker: node-modules

changesetBaseRefs:
  - "release"
  - "origin/release"

npmRegistries:
  "https://artifactory.comcast.com/artifactory/api/npm/Lightning-npm-releases":
    npmAlwaysAuth: true
    npmAuthToken: "${LEGACY_TOKEN:-fallback}"

npmScopes:
  lightning:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://artifactory.comcast.com/artifactory/api/npm/Lightning-npm-releases"
    npmRegistryServer: "https://artifactory.comcast.com/artifactory/api/npm/Lightning-npm"
  suite-themes:
    npmRegistryServer: "https://artifactory.comcast.com/artifactory/api/npm/xds-npm"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs