---
platform: linux
inputs:
  - name: source-repo
outputs:
  - name: source-repo/dist
caches:
  - path: source-repo/node_modules
image_resource:
  type: cf
  source:
    api: https://api.ame1-g2.cf.comcast.net
run:
  path: bash
  args: [ ./ci/tasks/cloudfoundry.sh ]
  dir: ./source-repo
