---
platform: linux
inputs:
  - name: source-repo
outputs:
  - name: build
  - name: node_modules
image_resource:
  type: docker-image
  source:
    repository: node
    tag: 16.9.1
run:
  path: ./ci/tasks/install.sh
  dir: ./source-repo
