platform: linux
inputs:
  - name: source-repo
outputs:
  - name: source-repo
  - name: comment
image_resource:
  type: docker-image
  source:
    repository: hub.comcast.net/ottx/cypress-included-10.3.0
    tag: latest
params:
      # AWS credentials
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_BUCKET:
      VRT_APIKEY:
      VRT_PROJECT:
      TZ: US/Eastern
run:
  path: ./ci/tasks/run-tests.sh
  dir: ./source-repo
