export default {
  functionalStandard: 'cubic-bezier(0, 0, 1, 1)',
  functionalStandardDelay: 0,
  functionalStandardDuration: 0.25,
  functionalEntrance: 'cubic-bezier(0, 0, 1, 1)',
  functionalEntranceDelay: 0,
  functionalEntranceDuration: 0.25,
  functionalExit: 'cubic-bezier(0, 0, 1, 1)',
  functionalExitDelay: 0,
  functionalExitDuration: 0.25,
  expressiveStandard: 'cubic-bezier(0, 0, 1, 1)',
  expressiveStandardDelay: 0,
  expressiveStandardDuration: 0.25,
  expressiveEntrance: 'cubic-bezier(0, 0, 1, 1)',
  expressiveEntranceDelay: 0,
  expressiveEntranceDuration: 0.25,
  expressiveExit: 'cubic-bezier(0, 0, 1, 1)',
  expressiveExitDelay: 0,
  expressiveExitDuration: 0.25,
  emphasizedStandard: 'cubic-bezier(0, 0, 1, 1)',
  emphasizedStandardDelay: 0,
  emphasizedStandardDuration: 0.25,
  emphasizedEntrance: 'cubic-bezier(0, 0, 1, 1)',
  emphasizedEntranceDelay: 0,
  emphasizedEntranceDuration: 0.25,
  emphasizedExit: 'cubic-bezier(0, 0, 1, 1)',
  emphasizedExitDelay: 0,
  emphasizedExitDuration: 0.25
};
