export default {
  durationNone: 0,
  durationXFast: 0.1,
  durationFast: 0.25,
  durationNormal: 0.5,
  durationSlow: 0.75,
  durationXSlow: 0.9,
  delayNone: 0,
  delayXFast: 0.01,
  delayFast: 0.025,
  delayNormal: 0.05,
  delaySlow: 0.075,
  delayXSlow: 0.09,
  functionalStandard: 'cubic-bezier(0, 0, 1, 1)',
  functionalStandardDelay: 0,
  functionalStandardDuration: 0.25,
  functionalEntrance: 'cubic-bezier(0, 0, 1, 1)',
  functionalEntranceDelay: 0,
  functionalEntranceDuration: 0.25,
  functionalExit: 'cubic-bezier(0, 0, 1, 1)',
  functionalExitDelay: 0,
  functionalExitDuration: 0.25,
  expressiveStandard: 'cubic-bezier(0, 0, 1, 1)',
  expressiveStandardDelay: 0,
  expressiveStandardDuration: 0.25,
  expressiveEntrance: 'cubic-bezier(0, 0, 1, 1)',
  expressiveEntranceDelay: 0,
  expressiveEntranceDuration: 0.25,
  expressiveExit: 'cubic-bezier(0, 0, 1, 1)',
  expressiveExitDelay: 0,
  expressiveExitDuration: 0.25,
  emphasizedStandard: 'cubic-bezier(0, 0, 1, 1)',
  emphasizedStandardDelay: 0,
  emphasizedStandardDuration: 0.25,
  emphasizedEntrance: 'cubic-bezier(0, 0, 1, 1)',
  emphasizedEntranceDelay: 0,
  emphasizedEntranceDuration: 0.25,
  emphasizedExit: 'cubic-bezier(0, 0, 1, 1)',
  emphasizedExitDelay: 0,
  emphasizedExitDuration: 0.25
};
