import ALPHAS from './alphas';

export default {
  material: ['#000033', ALPHAS.primary],
  surface: ['#02026b', ALPHAS.primary],
  surfaceSecondary: ['#02026b', ALPHAS.secondary],
  surfaceTertiary: ['#02026b', ALPHAS.tertiary],
  surfaceDisabled: ['#02026b', ALPHAS.inactive],
  surfaceGhost: ['#02026b', ALPHAS.none],
  fillNeutral1: ['#ebf1ff', ALPHAS.primary],
  fillNeutral1Secondary: ['#ebf1ff', ALPHAS.secondary],
  fillNeutral1Tertiary: ['#ebf1ff', ALPHAS.tertiary],
  fillNeutral1Disabled: ['#ebf1ff', ALPHAS.inactive],
  fillNeutral1Ghost: ['#ebf1ff', ALPHAS.none],
  fillNeutral2: ['#93a9fd', ALPHAS.primary],
  fillInverse1: ['#000033', ALPHAS.primary],
  fillInverse1Secondary: ['#000033', ALPHAS.secondary],
  fillInverse1Tertiary: ['#000033', ALPHAS.tertiary],
  fillInverse1Disabled: ['#000033', ALPHAS.inactive],
  fillInverse1Ghost: ['#000033', ALPHAS.none],
  fillInverse2: ['#4c5ff7', ALPHAS.primary],
  fillBrand: ['#93a9fd', ALPHAS.primary],
  fillBrandSecondary: ['#93a9fd', ALPHAS.secondary],
  fillBrandTertiary: ['#93a9fd', ALPHAS.tertiary],
  fillBrandDisabled: ['#93a9fd', ALPHAS.inactive],
  fillBrandGhost: ['#93a9fd', ALPHAS.none],
  overlay: ['#000033', ALPHAS.secondary],
  surfaceFocus: ['#FFFFFF', ALPHAS.primary],
  surfaceFocusSoft: ['#FFFFFF', ALPHAS.tertiary],
  fillNeutralFocus: ['#FFFFFF', ALPHAS.primary],
  fillNeutralFocusSoft: ['#FFFFFF', ALPHAS.tertiary],
  fillInverseFocus: ['#48474b', ALPHAS.primary],
  fillInverseFocusSoft: ['#48474b', ALPHAS.tertiary],
  fillBrandFocus: ['#becffe', ALPHAS.primary],
  fillBrandFocusSoft: ['#becffe', ALPHAS.tertiary],
  gray: ['#8B8B97', ALPHAS.primary],
  red: ['#E74C3C ', ALPHAS.primary],
  orange: ['#DC7633', ALPHAS.primary],
  yellow: ['#F7DC6F', ALPHAS.primary],
  green: ['#2ECC71', ALPHAS.primary],
  blue: ['#93a9fd', ALPHAS.primary],
  purple: ['#663399', ALPHAS.primary]
};
