export default {
  emphasizedEntrance: 'cubic-bezier(0.1, 0.4, 0.16, 1.4)',
  emphasizedEntranceDelay: 0,
  emphasizedEntranceDuration: 0.5,
  emphasizedExit: 'cubic-bezier(0.8, -0.4, 0.8, 0.4)',
  emphasizedExitDelay: 0,
  emphasizedExitDuration: 0.5,
  emphasizedStandard: 'cubic-bezier(0.8, -0.4, 0.2, 1.4)',
  emphasizedStandardDelay: 0,
  emphasizedStandardDuration: 0.5,
  expressiveEntrance: 'cubic-bezier(0, 0, 0.15, 1)',
  expressiveEntranceDelay: 0,
  expressiveEntranceDuration: 0.5,
  expressiveExit: 'cubic-bezier(0.9, 0, 1, 1)',
  expressiveExitDelay: 0,
  expressiveExitDuration: 0.5,
  expressiveStandard: 'cubic-bezier(0.6, 0, 0.1, 1)',
  expressiveStandardDelay: 0,
  expressiveStandardDuration: 0.5,
  functionalEntrance: 'cubic-bezier(0, 0, 0.4, 1)',
  functionalEntranceDelay: 0,
  functionalEntranceDuration: 0.5,
  functionalExit: 'cubic-bezier(0.4, 0, 1, 1)',
  functionalExitDelay: 0,
  functionalExitDuration: 0.5,
  functionalStandard: 'cubic-bezier(0.4, 0.15, 0.1, 1)',
  functionalStandardDelay: 0,
  functionalStandardDuration: 0.5
};
