const COLOR_PALETTE = {
  grey: {
    0: '#FFFFFF',
    5: '#F6F6F9',
    10: '#ECECF2',
    20: '#CECEDA',
    30: '#B1B1BD',
    40: '#8B8B97',
    50: '#62626C',
    60: '#484851',
    70: '#35353B',
    80: '#232328',
    90: '#141417',
    100: '#000000'
  },
  red: {
    5: '#F2D9E1',
    10: '#FF99BA',
    20: '#FF6194',
    30: '#FF3878',
    40: '#F0004D',
    50: '#E6004A',
    60: '#B7023C',
    70: '#8F002F',
    80: '#660021',
    90: '#2A120E'
  },
  orange: {
    5: '#F2E1D9',
    10: '#FFB68F',
    20: '#FF8D52',
    30: '#FF6F24',
    40: '#F95600',
    50: '#E64F00',
    60: '#B33D00',
    70: '#A33800',
    80: '#8F3100',
    90: '#2A170E'
  },
  yellow: {
    5: '#F2EAD9',
    10: '#FFD88A',
    20: '#FFC95C',
    30: '#FFB829',
    40: '#FFAA00',
    50: '#B87700',
    60: '#8F5D00',
    70: '#7A5000',
    80: '#664200',
    90: '#1F180A'
  },
  green: {
    5: '#D9F2EA',
    10: '#78E3BF',
    20: '#0AC284',
    30: '#009965',
    40: '#008F5E',
    50: '#008558',
    60: '#006851',
    70: '#005240',
    80: '#003328',
    90: '#0A1F18'
  },
  blue: {
    5: '#D9E1F2',
    10: '#8BAFF9',
    20: '#4784FF',
    30: '#3376FF',
    40: '#2970FF',
    50: '#1F69FF',
    60: '#0051D0',
    70: '#0040A3',
    80: '#003485',
    90: '#111A32'
  },
  purple: {
    5: '#E3E0F4',
    10: '#BAA8FA',
    20: '#9378F8',
    30: '#805FF6',
    40: '#704BF7',
    50: '#6138F5',
    60: '#4D00BD',
    70: '#3A0092',
    80: '#28006A',
    90: '#1E1236'
  }
};

const ALPHAS_LIGHT = {
  primary: 100,
  secondary: 60,
  inactive: 30,
  tertiary: 15,
  none: 0
};

const ALPHAS_DARK = {
  primary: 100,
  secondary: 60,
  inactive: 30,
  tertiary: 15,
  none: 0
};

export const COLORS_LIGHT = {
  materialNegative: [COLOR_PALETTE.red['5'], ALPHAS_LIGHT.primary],
  materialCaution: [COLOR_PALETTE.orange['5'], ALPHAS_LIGHT.primary],
  materialPositive: [COLOR_PALETTE.green['5'], ALPHAS_LIGHT.primary],
  materialInfo: [COLOR_PALETTE.purple['5'], ALPHAS_LIGHT.primary],
  fillNegativeBase: [COLOR_PALETTE.red['60'], ALPHAS_LIGHT.primary],
  fillNegativeHover: [COLOR_PALETTE.red['70'], ALPHAS_LIGHT.primary],
  fillNegativeDown: [COLOR_PALETTE.red['80'], ALPHAS_LIGHT.primary],
  fillNegativeFocus: [COLOR_PALETTE.red['70'], ALPHAS_LIGHT.primary],
  fillCautionBase: [COLOR_PALETTE.orange['60'], ALPHAS_LIGHT.primary],
  fillCautionHover: [COLOR_PALETTE.orange['70'], ALPHAS_LIGHT.primary],
  fillCautionDown: [COLOR_PALETTE.orange['80'], ALPHAS_LIGHT.primary],
  filCautionFocus: [COLOR_PALETTE.orange['70'], ALPHAS_LIGHT.primary],
  fillPositiveBase: [COLOR_PALETTE.green['60'], ALPHAS_LIGHT.primary],
  fillPositiveHover: [COLOR_PALETTE.green['70'], ALPHAS_LIGHT.primary],
  fillPositiveDown: [COLOR_PALETTE.green['80'], ALPHAS_LIGHT.primary],
  fillPositiveFocus: [COLOR_PALETTE.green['70'], ALPHAS_LIGHT.primary],
  fillInfoBase: [COLOR_PALETTE.blue['60'], ALPHAS_LIGHT.primary],
  fillInfoHover: [COLOR_PALETTE.blue['70'], ALPHAS_LIGHT.primary],
  fillInfoDown: [COLOR_PALETTE.blue['80'], ALPHAS_LIGHT.primary],
  fillInfoFocus: [COLOR_PALETTE.blue['70'], ALPHAS_LIGHT.primary],
  fillNeutralBase: [COLOR_PALETTE.grey['90'], ALPHAS_LIGHT.primary],
  fillNeutralHover: [COLOR_PALETTE.grey['70'], ALPHAS_LIGHT.primary],
  fillNeutralDown: [COLOR_PALETTE.grey['60'], ALPHAS_LIGHT.primary],
  fillNeutralFocus: [COLOR_PALETTE.grey['70'], ALPHAS_LIGHT.primary],
  fillInverseBase: [COLOR_PALETTE.grey['5'], ALPHAS_LIGHT.primary],
  fillInverseHover: [COLOR_PALETTE.grey['0'], ALPHAS_LIGHT.primary],
  fillInverseDown: [COLOR_PALETTE.grey['20'], ALPHAS_LIGHT.primary],
  fillInverseFocus: [COLOR_PALETTE.grey['0'], ALPHAS_LIGHT.primary],
  strokeNegativeBase: [COLOR_PALETTE.red['50'], ALPHAS_LIGHT.primary],
  strokeNegativeHover: [COLOR_PALETTE.red['70'], ALPHAS_LIGHT.primary],
  strokeNegativeDown: [COLOR_PALETTE.red['80'], ALPHAS_LIGHT.primary],
  strokeNegativeFocus: [COLOR_PALETTE.red['70'], ALPHAS_LIGHT.primary],
  strokeCautionBase: [COLOR_PALETTE.orange['50'], ALPHAS_LIGHT.primary],
  strokeCautionHover: [COLOR_PALETTE.orange['70'], ALPHAS_LIGHT.primary],
  strokeCautionDown: [COLOR_PALETTE.orange['80'], ALPHAS_LIGHT.primary],
  strokeCautionFocus: [COLOR_PALETTE.orange['70'], ALPHAS_LIGHT.primary],
  strokePositiveBase: [COLOR_PALETTE.green['50'], ALPHAS_LIGHT.primary],
  strokePositiveHover: [COLOR_PALETTE.green['70'], ALPHAS_LIGHT.primary],
  strokePositiveDown: [COLOR_PALETTE.green['80'], ALPHAS_LIGHT.primary],
  strokePositiveFocus: [COLOR_PALETTE.green['70'], ALPHAS_LIGHT.primary],
  strokeInfoBase: [COLOR_PALETTE.blue['50'], ALPHAS_LIGHT.primary],
  strokeInfoHover: [COLOR_PALETTE.blue['70'], ALPHAS_LIGHT.primary],
  strokeInfoDown: [COLOR_PALETTE.blue['80'], ALPHAS_LIGHT.primary],
  strokeInfoFocus: [COLOR_PALETTE.blue['70'], ALPHAS_LIGHT.primary],
  strokeNeutralBase: [COLOR_PALETTE.grey['90'], ALPHAS_LIGHT.primary],
  strokeNeutralHover: [COLOR_PALETTE.grey['70'], ALPHAS_LIGHT.primary],
  strokeNeutralDown: [COLOR_PALETTE.grey['60'], ALPHAS_LIGHT.primary],
  strokeNeutralFocus: [COLOR_PALETTE.grey['70'], ALPHAS_LIGHT.primary],
  strokeInverseBase: [COLOR_PALETTE.grey['5'], ALPHAS_LIGHT.primary],
  strokeInverseHover: [COLOR_PALETTE.grey['0'], ALPHAS_LIGHT.primary],
  strokeInverseDown: [COLOR_PALETTE.grey['20'], ALPHAS_LIGHT.primary],
  strokeInverseFocus: [COLOR_PALETTE.grey['0'], ALPHAS_LIGHT.primary],
  textNegativeBase: [COLOR_PALETTE.red['60'], ALPHAS_LIGHT.primary],
  textNegativeHover: [COLOR_PALETTE.red['70'], ALPHAS_LIGHT.primary],
  textNegativeDown: [COLOR_PALETTE.red['80'], ALPHAS_LIGHT.primary],
  textNegativeFocus: [COLOR_PALETTE.red['70'], ALPHAS_LIGHT.primary],
  textCautionBase: [COLOR_PALETTE.orange['60'], ALPHAS_LIGHT.primary],
  textCautionHover: [COLOR_PALETTE.orange['70'], ALPHAS_LIGHT.primary],
  textCautionDown: [COLOR_PALETTE.orange['80'], ALPHAS_LIGHT.primary],
  textCautionFocus: [COLOR_PALETTE.orange['70'], ALPHAS_LIGHT.primary],
  textPositiveBase: [COLOR_PALETTE.green['60'], ALPHAS_LIGHT.primary],
  textPositiveHover: [COLOR_PALETTE.green['70'], ALPHAS_LIGHT.primary],
  textPositiveDown: [COLOR_PALETTE.green['80'], ALPHAS_LIGHT.primary],
  textPositiveFocus: [COLOR_PALETTE.green['70'], ALPHAS_LIGHT.primary],
  textInfoBase: [COLOR_PALETTE.blue['60'], ALPHAS_LIGHT.primary],
  textInfoHover: [COLOR_PALETTE.blue['70'], ALPHAS_LIGHT.primary],
  textInfoDown: [COLOR_PALETTE.blue['80'], ALPHAS_LIGHT.primary],
  textInfoFocus: [COLOR_PALETTE.blue['70'], ALPHAS_LIGHT.primary],
  textNeutralBase: [COLOR_PALETTE.grey['90'], ALPHAS_LIGHT.primary],
  textNeutralHover: [COLOR_PALETTE.grey['70'], ALPHAS_LIGHT.primary],
  textNeutralDown: [COLOR_PALETTE.grey['60'], ALPHAS_LIGHT.primary],
  textNeutralFocus: [COLOR_PALETTE.grey['70'], ALPHAS_LIGHT.primary],
  textInverseBase: [COLOR_PALETTE.grey['5'], ALPHAS_LIGHT.primary],
  textInverseHover: [COLOR_PALETTE.grey['0'], ALPHAS_LIGHT.primary],
  textInverseDown: [COLOR_PALETTE.grey['20'], ALPHAS_LIGHT.primary],
  textInverseFocus: [COLOR_PALETTE.grey['0'], ALPHAS_LIGHT.primary]
};

export const COLORS_DARK = {
  materialNegative: [COLOR_PALETTE.red['90'], ALPHAS_DARK.primary],
  materialCaution: [COLOR_PALETTE.orange['90'], ALPHAS_DARK.primary],
  materialPositive: [COLOR_PALETTE.green['90'], ALPHAS_DARK.primary],
  materialInfo: [COLOR_PALETTE.purple['90'], ALPHAS_DARK.primary],
  fillNegativeBase: [COLOR_PALETTE.red['30'], ALPHAS_DARK.primary],
  fillNegativeHover: [COLOR_PALETTE.red['20'], ALPHAS_DARK.primary],
  fillNegativeDown: [COLOR_PALETTE.red['10'], ALPHAS_DARK.primary],
  fillNegativeFocus: [COLOR_PALETTE.red['20'], ALPHAS_DARK.primary],
  fillCautionBase: [COLOR_PALETTE.orange['30'], ALPHAS_DARK.primary],
  fillCautionHover: [COLOR_PALETTE.orange['20'], ALPHAS_DARK.primary],
  fillCautionDown: [COLOR_PALETTE.orange['10'], ALPHAS_DARK.primary],
  filCautionFocus: [COLOR_PALETTE.orange['20'], ALPHAS_DARK.primary],
  fillPositiveBase: [COLOR_PALETTE.green['30'], ALPHAS_DARK.primary],
  fillPositiveHover: [COLOR_PALETTE.green['20'], ALPHAS_DARK.primary],
  fillPositiveDown: [COLOR_PALETTE.green['10'], ALPHAS_DARK.primary],
  fillPositiveFocus: [COLOR_PALETTE.green['20'], ALPHAS_DARK.primary],
  fillInfoBase: [COLOR_PALETTE.blue['30'], ALPHAS_DARK.primary],
  fillInfoHover: [COLOR_PALETTE.blue['20'], ALPHAS_DARK.primary],
  fillInfoDown: [COLOR_PALETTE.blue['10'], ALPHAS_DARK.primary],
  fillInfoFocus: [COLOR_PALETTE.blue['20'], ALPHAS_DARK.primary],
  fillNeutralBase: [COLOR_PALETTE.grey['5'], ALPHAS_DARK.primary],
  fillNeutralHover: [COLOR_PALETTE.grey['0'], ALPHAS_DARK.primary],
  fillNeutralDown: [COLOR_PALETTE.grey['20'], ALPHAS_DARK.primary],
  fillNeutralFocus: [COLOR_PALETTE.grey['0'], ALPHAS_DARK.primary],
  fillInverseBase: [COLOR_PALETTE.grey['90'], ALPHAS_DARK.primary],
  fillInverseHover: [COLOR_PALETTE.grey['70'], ALPHAS_DARK.primary],
  fillInverseDown: [COLOR_PALETTE.grey['60'], ALPHAS_DARK.primary],
  fillInverseFocus: [COLOR_PALETTE.grey['70'], ALPHAS_DARK.primary],
  strokeNegativeBase: [COLOR_PALETTE.red['40'], ALPHAS_DARK.primary],
  strokeNegativeHover: [COLOR_PALETTE.red['20'], ALPHAS_DARK.primary],
  strokeNegativeDown: [COLOR_PALETTE.red['10'], ALPHAS_DARK.primary],
  strokeNegativeFocus: [COLOR_PALETTE.red['20'], ALPHAS_DARK.primary],
  strokeCautionBase: [COLOR_PALETTE.orange['40'], ALPHAS_DARK.primary],
  strokeCautionHover: [COLOR_PALETTE.orange['20'], ALPHAS_DARK.primary],
  strokeCautionDown: [COLOR_PALETTE.orange['10'], ALPHAS_DARK.primary],
  strokeCautionFocus: [COLOR_PALETTE.orange['20'], ALPHAS_DARK.primary],
  strokePositiveBase: [COLOR_PALETTE.green['40'], ALPHAS_DARK.primary],
  strokePositiveHover: [COLOR_PALETTE.green['20'], ALPHAS_DARK.primary],
  strokePositiveDown: [COLOR_PALETTE.green['10'], ALPHAS_DARK.primary],
  strokePositiveFocus: [COLOR_PALETTE.green['20'], ALPHAS_DARK.primary],
  strokeInfoBase: [COLOR_PALETTE.blue['40'], ALPHAS_DARK.primary],
  strokeInfoHover: [COLOR_PALETTE.blue['20'], ALPHAS_DARK.primary],
  strokeInfoDown: [COLOR_PALETTE.blue['10'], ALPHAS_DARK.primary],
  strokeInfoFocus: [COLOR_PALETTE.blue['20'], ALPHAS_DARK.primary],
  strokeNeutralBase: [COLOR_PALETTE.grey['5'], ALPHAS_DARK.primary],
  strokeNeutralHover: [COLOR_PALETTE.grey['0'], ALPHAS_DARK.primary],
  strokeNeutralDown: [COLOR_PALETTE.grey['20'], ALPHAS_DARK.primary],
  strokeNeutralFocus: [COLOR_PALETTE.grey['0'], ALPHAS_DARK.primary],
  strokeInverseBase: [COLOR_PALETTE.grey['90'], ALPHAS_DARK.primary],
  strokeInverseHover: [COLOR_PALETTE.grey['70'], ALPHAS_DARK.primary],
  strokeInverseDown: [COLOR_PALETTE.grey['60'], ALPHAS_DARK.primary],
  strokeInverseFocus: [COLOR_PALETTE.grey['70'], ALPHAS_DARK.primary],
  textNegativeBase: [COLOR_PALETTE.red['30'], ALPHAS_DARK.primary],
  textNegativeHover: [COLOR_PALETTE.red['20'], ALPHAS_DARK.primary],
  textNegativeDown: [COLOR_PALETTE.red['10'], ALPHAS_DARK.primary],
  textNegativeFocus: [COLOR_PALETTE.red['20'], ALPHAS_DARK.primary],
  textCautionBase: [COLOR_PALETTE.orange['30'], ALPHAS_DARK.primary],
  textCautionHover: [COLOR_PALETTE.orange['20'], ALPHAS_DARK.primary],
  textCautionDown: [COLOR_PALETTE.orange['10'], ALPHAS_DARK.primary],
  textCautionFocus: [COLOR_PALETTE.orange['20'], ALPHAS_DARK.primary],
  textPositiveBase: [COLOR_PALETTE.green['30'], ALPHAS_DARK.primary],
  textPositiveHover: [COLOR_PALETTE.green['20'], ALPHAS_DARK.primary],
  textPositiveDown: [COLOR_PALETTE.green['10'], ALPHAS_DARK.primary],
  textPositiveFocus: [COLOR_PALETTE.green['20'], ALPHAS_DARK.primary],
  textInfoBase: [COLOR_PALETTE.blue['30'], ALPHAS_DARK.primary],
  textInfoHover: [COLOR_PALETTE.blue['20'], ALPHAS_DARK.primary],
  textInfoDown: [COLOR_PALETTE.blue['10'], ALPHAS_DARK.primary],
  textInfoFocus: [COLOR_PALETTE.blue['20'], ALPHAS_DARK.primary],
  textNeutralBase: [COLOR_PALETTE.grey['5'], ALPHAS_DARK.primary],
  textNeutralHover: [COLOR_PALETTE.grey['0'], ALPHAS_DARK.primary],
  textNeutralDown: [COLOR_PALETTE.grey['20'], ALPHAS_DARK.primary],
  textNeutralFocus: [COLOR_PALETTE.grey['0'], ALPHAS_DARK.primary],
  textInverseBase: [COLOR_PALETTE.grey['90'], ALPHAS_DARK.primary],
  textInverseHover: [COLOR_PALETTE.grey['70'], ALPHAS_DARK.primary],
  textInverseDown: [COLOR_PALETTE.grey['60'], ALPHAS_DARK.primary],
  textInverseFocus: [COLOR_PALETTE.grey['70'], ALPHAS_DARK.primary]
};
