# This workflow will run tests using node and then publish a package to both NPM and GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages
# Copyright (c) 2019 GitHub
# Licensed under the MIT license

name: Node.js Package

on:
  push:
    branches:
      - release
      - beta
      - next

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - run: npm ci
      - run: npm run test

  publish-npm:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npx semantic-release --no-ci --repository-url git@github.com:rdkcentral/Lightning-UI-Components.git
        env:
          GITHUB_TOKEN: ${{secrets.GIT_PUBLISH_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npx semantic-release --no-ci --repository-url git@github.com:rdkcentral/Lightning-UI-Components.git
        env:
          GITHUB_TOKEN: ${{secrets.GIT_PUBLISH_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
